### ISSUE TITLE
Two points of contact

### ISSUE THREAD

**Issue by fcanas** [erichoracek/Motif#1]
I'm looking at how a button is styled in the button example:

``` objc
- (UIButton *)saveButton
{
    if (!_saveButton) {
        self.saveButton = ({
            UIButton *button = [UIButton buttonWithType:UIButtonTypeSystem];
            [button aut_applyThemeClassWithName:ThemeClassNames.PrimaryButton fromTheme:self.aut_theme];
            [button setTitle:NSLocalizedString(@"Save", nil) forState:UIControlStateNormal];
            button;
        });
    }
    return _saveButton;
}
```

Especially, the line 

``` objc
[button aut_applyThemeClassWithName:ThemeClassNames.PrimaryButton fromTheme:self.aut_theme];
```

There are two parts of the library in use here. I usually consider that suspicious unless it's providing a clear point of flexibility. And even then, it's a good opportunity for a convenience method that "just works". So I suggest something like

``` objc
[self.aut_theme applyClassName:ThemeClassNames.PrimaryButton toButton:button];
```

or 

``` objc
[self.aut_theme applyClassName:ThemeClassNames.PrimaryButton toObject:button];
```

---

But maybe applying a class shouldn't be the responsibility of a theme. I see there is an AUTThemeApplier object. So maybe this is just a problem with the button example.

But I don't see signatures in the theme applier that are what I would want:

``` objc
self.themeApplier = [AUTThemeApplier applierWithTheme:AUTTheme];
...
[self.themeApplier applyClassName:ThemeClassNames.PrimaryButton toObject:button];
```

or 

``` objc
self.themeApplier = [AUTThemeApplier applierWithTheme:AUTTheme];
...
stylePrimaryButton = [AUTThemeApplier applierBlockForClassName:ThemeClassNames.PrimaryButton];
stylePrimaryButton(button);
```

What some of these methods that I'm looking for amount to a loose object-oriented method currying. I'll think about what kind of interface I'd like to use, and how I'd like to use it some more before going on about that...

**Comment by erichoracek** [comment]
Ah yes! This is exact issue that I've been working on changing over the past few days as I told you in my last twitter DM. In my most recent commits, I've created a `AUTThemeApplier` class that is responsible for applying the theme rather than the applying mechanism existing as a category on `NSObject` for the same reasons that you specified as well as a couple that have to do with enabling dynamic theming. Let me know what you think—I've updated the buttons example projects and created another that includes dynamic theming. They both now use the new API, and the old one has been deleted. It now looks as follows:

``` obj-c
[self.themeApplier applyClassWithName:ThemeClassNames.PrimaryButton toObject:button];
```

Take a look and let me know what you think.
